on:
    issues:
      types:
        - opened
jobs:
    label_issue:
      runs-on: ubuntu-latest
      steps:
        - env:
            GH_ENV: ${{ github }}
          run: |
            echo $GH_ENV